### ISSUE TITLE
Day-7 Hangman Project

### ISSUE THREAD

**Issue by ghost** [BigJellyDog/100_Days_of_Code#1]
Hi, I was taught to become good at coding, you have to test your code with lots of positive and negative scenarios such as what would happen if a user doesn't follow the rules like entering numbers where a letter or a word is required.
I noticed in your hangman, that you weren't considering that, and honestly thinking of what could with our codes help us build lasting solutions to problems. So I figured out you might want to fix the solution below. Instead of accepting number or numbers as input and penalizing them, why not continue to prompt them without penalizing them until they enter the correct input

![image](https://github.com/BigJellyDog/100_Days_of_Code/assets/114434873/763cda52-e927-4951-ae1a-9f1fbd3456d4)
![image](https://github.com/BigJellyDog/100_Days_of_Code/assets/114434873/5ec998f1-484b-467e-a9d7-7daca2f91953)

564 is obviously not a word and 2 is not a letter. So, prompt them to enter the correct stuff

**Comment by BigJellyDog** [comment]
Hey, really nice of you to text me feedback, foremost, thanks.
I fixed the bug, and now it's asking the user again until he's going to
type letters, and because of that i also found a bug that i didn't notice
before.

Wish you a nice day
